### ISSUE TITLE
Adding support to remove prefetch and creating a gui 

### ISSUE THREAD

**Issue by Louis047** [Adithya4720/Enhancement-Bot-for-Optimizing-Computer-Performance#1]
Hey,   
Glad that you have created a Temp Cleaner to reduce workload for people like me. Although there are certain files which have to be cleared too in order for the system to run well and responsive. 'Prefetch' directory is one among them. I'll provide you the system path here so that you can add it to your code: C:\Windows\Prefetch. And also, if am too bored to do anything, i'll try to contribute to this project by making an user interface for your Cleaner. Just lemme know if the above works.

Oh yeah, a bonus one. There's a cmd command for clearing DNS Cache in case if there's any network overload (useful for secure yet shit connections like our Amrita-WiFi): ipconfig /flushdns, try to add this too :)

Prefetch:
![image](https://github.com/Adithya4720/Bot-for-cleaning-temporary-file/assets/115528443/e8878ec8-8f2b-4bb7-ae20-e45609e0c2e7)

CMD Command to clear DNS Cache: (Should be Run as Admin):
![image](https://github.com/Adithya4720/Bot-for-cleaning-temporary-file/assets/115528443/e9e3206b-326c-4d2c-94d8-915591944299)

**Comment by hegdeadithyak** [comment]
Ahh Sure!! Create a PR after adding it I'll merge it into the application.
